spring.application.name=notificacao

server.port=8081

#Config RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#Custom config RABBITMQ
rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.queue.name=pedidos.v1.pedido-criado.gerar-notificacao